version: '3.8'

services:

  user-service:
    container_name: mcs_users-service
    image: pm44019/mcs_users-service:v1.0.1
    build:
      context: .
      dockerfile: mcs_users-service/Dockerfile
    depends_on:
      - db-postgres-users
      - eureka-server
  
  order-service:
    container_name: mcs_orders-service
    image: pm44019/mcs_orders-service:v1.0.1
    build:
      context: .
      dockerfile: mcs_orders-service/Dockerfile
    depends_on:
      - db-mysql-orders
      - eureka-server
  
  product-service:
    container_name: mcs_products-service
    image: pm44019/mcs_products-service:v1.0.1
    build:
      context: .
      dockerfile: mcs_products-service/Dockerfile
    depends_on:
      - db-oracle-product
      - eureka-server

  eureka-server:
    container_name: eureka-server
    image: pm44019/eureka-server:latest
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
  
  api-gateway:
    container_name: api-gateway
    image: pm44019/api-gateway:latest
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    depends_on:
      - eureka-server
  
  bff-web:
    container_name: bff_web-service
    image: pm44019/bff_web-service:latest
    build:
      context: .
      dockerfile: bff_web-service/Dockerfile
    depends_on:
      - eureka-server
  
  bff-mobile:
    container_name: bff_mobile-service
    image: pm44019/bff_mobile-service:latest
    build:
      context: .
      dockerfile: bff_mobile-service/Dockerfile
    depends_on:
      - eureka-server

  db-mysql-orders:
    image: mysql:latest
    restart: always
  
  db-postgres-users:
    image: postgres:alpine
    restart: always
  
  db-oracle-product:
    image: container-registry.oracle.com/database/enterprise:latest
    restart: always
  
  rabbitmq:
    image: rabbitmq:3-management
