version: '3.8'

services:

  user-service:
    ports:
      - 8081:8081
    networks:
      - my-network
  
  product-service:
    ports:
      - 8082:8082
    networks:
      - my-network
  
  order-service:
    ports:
      - 8083:8083
    networks:
      - my-network
  
  bff-mobile:
    ports:
      - 8002:8002
    networks:
      - my-network
  
  bff-web:
    ports:
      - 8001:8001
    networks:
      - my-network
  
  eureka-server:
    ports:
      - "8080:8080"
    networks:
        - my-network
  
  api-gateway:
    ports:
      - "8000:8000"
    depends_on:
      - eureka-server
    networks:
        - my-network
  
  db-mysql-orders:
    environment:
      MYSQL_ROOT_PASSWORD: 'p@ssw0rd'
      MYSQL_DATABASE: 'orders'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db-order:/var/lib/mysql
    networks:
        - my-network
  
  db-postgres-users:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - my-db-user:/var/lib/postgresql
    ports:
      - '5550:5432'
    networks:
        - my-network
  
  db-oracle-product:
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    ports:
      - '1521:1521'
    networks:
        - my-network
  
  rabbitmq:
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
        - my-network
  
volumes:
  my-db-order:
  my-db-user:
  oracle-data:
  oracle-backup:
  
networks:
  my-network:
    driver: bridge